### PR TITLE
Update curses_test.py

### PR DESCRIPTION
**Pull request by nostalgiaguy**

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Sure!

**Comment by nostalgiaguy** [comment]
hiiiiii  sethwood,
i want to work with u ,can u involved me in any simple java based project as i want to be a java devoloper and i also want to learn git-hub how it works and useful for us....
suggest me a way to talk with u like skype,glance,email,fb any
big big thanks to u...........

**Comment by sethwoodworth** [comment]
Hi Shubham! I'm not a great Java developer.  But I'd be happy to be involved with you on a python project.

**Comment by nostalgiaguy** [comment]
i will be happy if u help me to learn python...........

**Pull request merged**
